# Application Name
spring.application.name=Portfolio

# Database Connection (Using your new Root credentials)
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Idjdidfc8.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
# 'update' automatically creates/modifies tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Optional: Ensure Hibernate uses the correct MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect